### ISSUE TITLE
undefined as a string

### ISSUE THREAD

**Issue by reharik** [dtrelogan/react-formstate#7] opened 2016-09-08 21:13 UTC
Hi, this issue just nearly caused me to end my life.  I have calmed down now enough to figure out what code was doing it.

in the straight .js file, line 420 ironically enough 
    field.label = (this.labelPrefix || '') + props.label;

if this.labelPrefix and props.label are both undefined, you would logically believe that field.label is undefined.  And in fact, if you console.log(field.label) you get undefined.  
HOWEVER!!!! 
if you typeof field.label you get STRING!!!! so any conditionals you have that are checking label for falsey all will shit the bed! 
I see now that it's because you have the '' + undefined which must coerce undefined into a string.  
what would work properly would be 
        field.label = this.labelPrefix ? this.labelPrefix + props.label : props.label

Sorry for the caps and bangs.  I'm upset with live no you or javascript.  I'm calming down.
Thanks,
R

**Comment by dtrelogan** [comment] 2016-09-08 21:50
thanks for finding the bug. the issue is javascript coerces undefined to
'undefined'. so the suggested fix

field.label = this.labelPrefix ? this.labelPrefix + props.label :
props.label

could still return something like 'prefix undefined' ... though maybe that
makes sense if a label prefix is provided and a label isn't.

i'll spend some time this evening on this issue. thanks for bringing it to
my attention.

**Comment by reharik** [comment] 2016-09-08 21:54
You are right, same problem in reverse.  I was already spinning so I missed the reverse case :) 
it's going to be ugly.  seems like there should be a way to concat to strings without the danger of coercing undefined into a string.
I guess you could do 
this.labelPrefix = this.labelPrefix || '';
props.label = props.label || '';
field.label = this.labelPrefix + props.label:
but I suspect that could have other issues.

**Comment by dtrelogan** [comment] 2016-09-08 23:32
i think both of your suggestions would work well enough:

field.label = this.labelPrefix ? this.labelPrefix + props.label :
props.label

field.label = (this.labelPrefix || '') + (props.label || '')

i might lean toward the second option. empty string has truthiness equal to
false so i think it's good enough.

the comprehensive fix is probably to scrap the label prefix concept
entirely where react-formstate wouldn't generate any label prop whatsoever.
i don't think it's important enough to do a major fix though. i think the
truthiness of the label prop was the fundamental issue.

i'll update the code and the unit tests and push out a patch this evening.

**Comment by dtrelogan** [comment] 2016-09-09 01:21
alright i pushed a fix. thanks for the help!

**Closed** 2016-09-09 01:21 UTC

**Comment by reharik** [comment] 2016-09-09 13:38
awesome thanks,
r
